version: "3.8"

services:
  app:
    image: sms
    container_name: sms_app
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=school_db

  db:
    image: mysql:8.0
    container_name: sms_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=school_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

