services:
  app:
    build: .
    container_name: sms_app
    ports:
      - "8080:8080"
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=smsdb

  db:
    image: mysql:8.0
    container_name: sms_db
    environment:
      MYSQL_ROOT_PASSWORD=yourpassword
      MYSQL_DATABASE=smsdb
    ports:
      - "3307:3306"   # changed to avoid conflict with local MySQL
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
