name: Simple CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        run: |
          docker build -t my-3tier-app:latest .

      - name: Test run container
        run: |
          docker run -d -p 8080:8080 my-3tier-app:latest
          sleep 10
          docker ps
