name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build backend image
      - name: Build backend image
        run: docker build -t sms-backend:latest -f backend/Dockerfile ./backend

      # Build frontend image
      - name: Build frontend image
        run: docker build -t sms-frontend:latest -f frontend/Dockerfile ./frontend

      # (Optional) Build both with docker-compose
      # - name: Build all images using docker-compose
      #   run: docker compose build

      # Just to confirm images built successfully
      - name: List built images
        run: docker images
